---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: localhost:5001/apigateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: apigateway-env
      terminationGracePeriodSeconds: 180