---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: localhost:5001/microservice2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: microservice2-env
      terminationGracePeriodSeconds: 180