---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  labels:
    app: microservice2
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: microservice2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
      - name: microservice2
        image: microservice2:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: microservice2-env
      terminationGracePeriodSeconds: 180