---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: apigateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: apigateway-env
      terminationGracePeriodSeconds: 180