resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: apigateway-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - services__microservice1__http__0=http://microservice1:8080
    - services__microservice2__http__0=http://microservice2:8080
    - ASPNETCORE_URLS=http://+:8080;
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:4317


