---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: localhost:5001/microservice1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: microservice1-env
      terminationGracePeriodSeconds: 180