---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
  labels:
    app: microservice1
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: microservice1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
      - name: microservice1
        image: microservice1:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: microservice1-env
      terminationGracePeriodSeconds: 180